# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [master, temp/APPX-6129]
    # paths:
    #   - 'android/**'
    #   - 'e2e/appium/**'
    #   - 'loc/*'
    #   - 'native/ios/remitly/**'
    #   - 'packages/**'
    #   - '!packages/**/__tests__/**'
    #   - 'src/**'
    #   - '!src/**/__tests__/**'
    #   - 'types/**'
    #   - 'types-client/**'
    #   - 'yarn.lock'
  workflow_dispatch:
    inputs:
      should_run_android:
        description: "Run Android tests?"
        type: boolean
        required: true
        default: true

      browserstack_android_app_path:
        description: '[Optional] Android: Uploaded BrowserStack App Path (Eg. bs://<id>)'
        required: false
        default: ""

      should_run_ios:
        description: "Run iOS tests?"
        type: boolean
        required: true
        default: true

      browserstack_ios_app_path:
        description: '[Optional] iOS: Uploaded BrowserStack App Path (Eg. bs://<id>)'
        required: false
        default: ""

      spec_path:
        description: "Test Spec Path"
        required: false
        default: "./test/specs/*"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    if: |
      ${{ (github.event_name == 'workflow_dispatch') && (fromJSON(inputs.should_run_android) == true) && (inputs.browserstack_android_app_path == '' || inputs.browserstack_android_app_path == null) }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    if: |
      ${{ github.event_name == 'push' }} || (
        ${{ github.event_name == 'workflow_dispatch' && fromJSON(inputs.should_run_ios) == true && (inputs.browserstack_ios_app_path == '' || inputs.browserstack_ios_app_path == null) }}
      )
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
