# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  # schedule:
  #   - cron: '0 */3 * * *'  # Runs every 3 hours
  workflow_dispatch:
    inputs:
      should_run_android:
        description: "Run Android tests?"
        type: boolean
        required: true
        default: true

      browserstack_android_app_path:
        description: '[Optional] Android: Uploaded BrowserStack App Path (Eg. bs://<id>)'
        required: false
        default: ""

      should_run_ios:
        description: "Run iOS tests?"
        type: boolean
        required: true
        default: true

      browserstack_ios_app_path:
        description: '[Optional] iOS: Uploaded BrowserStack App Path (Eg. bs://<id>)'
        required: false
        default: ""

      spec_path:
        description: "Test Spec Path"
        required: false
        default: "./test/specs/*"

jobs:
  jobs_to_run:
    runs-on: ubuntu-latest
    env:
      THRESHOLD_TIME: 10800  # 3 hours in seconds

    outputs:
      build_android: ${{ steps.evaluate_jobs.outputs.build_android }}
      build_ios: ${{ steps.evaluate_jobs.outputs.build_ios }}
      run_android: ${{ steps.evaluate_jobs.outputs.run_android }}
      run_ios: ${{ steps.evaluate_jobs.outputs.run_ios }}

    steps:
      - uses: actions/checkout@v4
        if: ${{ github.event_name == 'schedule' }}
      - name: Get the latest commit timestamp
        id: get-commit-time
        if: ${{ github.event_name == 'schedule' }}
        run: |
          LAST_COMMIT_TIMESTAMP=$(git log -1 --format=%ct)
          CURRENT_TIMESTAMP=$(date +%s)
          TIME_DIFF=$((CURRENT_TIMESTAMP - LAST_COMMIT_TIMESTAMP))
          
          if [ "$TIME_DIFF" -gt {{ env.THRESHOLD_TIME }} ]; then
            echo "continue_checks=false" >> $GITHUB_ENV
            exit 0
          else
            OLDEST_COMMIT=$(git log --since="3 hours ago" --reverse --pretty=format:"%H" | head -n 1)
            echo "continue_checks=true" >> $GITHUB_ENV
            echo "oldest_commit=${OLDEST_COMMIT}" >> $GITHUB_ENV
          fi
      - name: Checks changes requiring E2E
        if: ${{ env.continue_checks == 'true' }}
        run: |
          echo "No changes detected"
          echo "changes_detected=false" >> "$GITHUB_ENV"
      - name: Evaluate jobs to execute
        id: evaluate_jobs
        run: |
          scheduled_changes=${{ github.event_name == 'schedule' && needs.check-changes.outputs.should-run == 'true' }}
          
          manual_run_android=${{ github.event_name == 'workflow_dispatch' && inputs.should_run_android == 'true'}}
          manual_run_ios=${{ github.event_name == 'workflow_dispatch' && inputs.should_run_ios == 'true'}}

          android_app_path_empty=$(( -z "${inputs.browserstack_android_app_path}" ))
          ios_app_path_empty=$(( -z "${inputs.browserstack_ios_app_path}" ))

          build_android=$((scheduled_changes || (manual_run_android && android_app_path_empty)))
          build_ios=$((scheduled_changes || (manual_run_ios && ios_app_path_empty)))
          
          run_android=$(( scheduled_changes || manual_run_android ))
          run_ios=$(( scheduled_changes || manual_run_ios ))

          echo "build_android=$build_android" >> "$GITHUB_ENV"
          echo "build_ios=$build_ios" >> "$GITHUB_ENV"
          echo "run_android=$run_android" >> "$GITHUB_ENV"
          echo "run_ios=$run_ios" >> "$GITHUB_ENV"
  print_outputs:
    runs-on: ubuntu-latest
    needs: jobs_to_run
    steps:
      - name: Print outputs
        run: |
          echo "build_android: $(( needs.jobs_to_run.outputs.build_android ))"
          echo "build_ios: $(( needs.jobs_to_run.outputs.build_ios ))"
          echo "run_android: $(( needs.jobs_to_run.outputs.run_android ))"
          echo "run_ios: $(( needs.jobs_to_run.outputs.run_ios ))"

          echo "build_android status: $(( needs.jobs_to_run.outputs.build_android == 'true' ))"
          echo "build_ios status: $(( needs.jobs_to_run.outputs.build_ios == 'true' ))"
          echo "run_android status: $(( needs.jobs_to_run.outputs.run_android == 'true' ))"
          echo "run_ios status: $(( needs.jobs_to_run.outputs.run_ios == 'true' ))"
